Drool\CurrencyBundle\Document\Currency:
    type: document
    collection: Currency
    repositoryClass: Drool\CurrencyBundle\Repository\CurrencyRepository
    fields:
        id:
            type: int
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        value:
            type: float
        shortName:
            type: string
            length: 255
            column: short_name
    lifecycleCallbacks: {  }
