Drool\CurrencyBundle\Document\Currency:
    type: document
    collection: Currency
    repositoryClass: Drool\CurrencyBundle\Repository\CurrencyRepository
    fields:
        id:
            id: true
        name:
            type: string
            length: 255
        value:
            type: float
        short_name:
            type: string
            length: 255
        is_virtual:
            type: boolean
            default: false
    lifecycleCallbacks: {  }
