<?php

namespace Drool\CurrencyBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * CurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends DocumentRepository
{
    public function findVirtual()
    {
//        $virtualCurrencies = array('IC', 'LD', 'TC', 'FG', 'FH', 'NN');
        $qb = $this->createQueryBuilder();
        $qb->addAnd($qb->expr()->field('is_virtual')->equals(true));
        return $qb->getQuery()->execute();
    }
}