<?php

namespace Drool\CurrencyBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * CurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends DocumentRepository
{
}